### ISSUE TITLE
Whitelist raw.githubusercontent.com and bitbucket.org

### ISSUE THREAD

**Issue by dm** [HorusTeknoloji/TR-PhishingList#12]
Makes no sense to block these o_0

**Comment by MertcanGokgoz** [comment]
Yes, There is a mistake :)

Thank you for your feedback

**Comment by MertcanGokgoz** [comment]
Fixed https://github.com/HorusTeknoloji/TR-PhishingList/commit/ab8eee144f73f415884c0f8a9fe72030eea1288e
