### ISSUE TITLE
s1.wp.com

### ISSUE THREAD

**Issue by p1r473** [HorusTeknoloji/TR-PhishingList#20]
Hi,
This domain is used for static assets on Wordpress. Blocking this breaks many Wordpress sites.

**Comment by MertcanGokgoz** [comment]
not on the list

**Comment by p1r473** [comment]
Sorry, got my GIthub repos mixed up again!!

**Comment by p1r473** [comment]
Sorry @MertcanGokgoz  I meant s0.wp.com

**Comment by MertcanGokgoz** [comment]
Thx, Fixed :)

**Comment by p1r473** [comment]
Np thanks!
