### ISSUE TITLE
1drv.ms

### ISSUE THREAD

**Issue by WaLLy3K** [HorusTeknoloji/TR-PhishingList#31]
`1drv.ms` is a shortlink used for Microsoft OneDrive files, and it would be appreciated if this entry could be reviewed and considered for removal.

Thanks!

**Comment by MertcanGokgoz** [comment]
https://github.com/HorusTeknoloji/TR-PhishingList/commit/d3ad52e33943854a58e355452f7a3f4a51e550a5
