### ISSUE TITLE
HTML garbage in file

### ISSUE THREAD

**Issue by bronger** [HorusTeknoloji/TR-PhishingList#50]
In the middle of url-lists.txt, there is

    <script type='text/javascript' src='https://sagadc.com/wp-content/plugins/kadence-blocks/dist/magnific.js?ver=1.9.12' id='magnific-popup-js'></script>

**Comment by MertcanGokgoz** [comment]
I don't know which of our sources it came from, thanks for reporting the situation.

fixed https://github.com/HorusTeknoloji/TR-PhishingList/commit/6c9befd7e418f7a22a5d43508c967a609540367e

We will investigate.
