### ISSUE TITLE
Yanlış Bloklama (false positive) ftpupload.net

### ISSUE THREAD

**Issue by sarptekbas** [HorusTeknoloji/TR-PhishingList#65]
Merhaba,

Blocklisti bir süredir kullanıyorum fakat kullandığım web hosting firmasının sunucusuna ftp ile bağlanamıyordum. Pi-Hole çalışan Raspberry Pi’da `pihole -q ftpupload.net` komutunu çalıştırınca bu blocklisti gösterdi. Sadece ftp yükleme sunucusunun domaini. Blocklistten silebilirseniz sevinirim.

**Comment by MertcanGokgoz** [comment]
Geçici olarak kaldırılmıştır.
